export const skills: Skill[] = [
    {
      name: "Laravel",
      level: "",
      type: "Framework",
      highlight: true,
      logo_url: "/skills/selected-skills/laravel.svg",
    },
    {
      name: "PHP",
      level: "",
      type: "Language",
      highlight: true,
      logo_url: "/skills/selected-skills/php.svg",
    },
    {
      name: "React",
      level: "",
      type: "Library",
      highlight: true,
      logo_url: "/skills/selected-skills/react.svg",
    },
    {
      name: "VSCode",
      level: "",
      type: "IDE",
      highlight: true,
      logo_url: "/skills/selected-skills/vscode.svg",
    },
    {
      name: "Docker",
      level: "",
      type: "Containerization",
      highlight: true,
      logo_url: "/skills/selected-skills/docker.svg",
    },
    {
      name: "TailwindCSS",
      level: "",
      type: "CSS",
      highlight: true,
      logo_url: "/skills/selected-skills/tailwindcss.svg",
    },
    {
      name: "Next.js",
      level: "",
      type: "Framework",
      highlight: true,
      logo_url: "/skills/selected-skills/nextjs.svg",
    },
    {
      name: "Redis",
      level: "",
      type: "Cache",
      highlight: true,
      logo_url: "/skills/selected-skills/redis.svg",
    },
    {
      name: "Typescript",
      level: "",
      type: "Language",
      highlight: true,
      logo_url: "/skills/selected-skills/typescript.svg",
    },
    {
      name: "Javascript",
      level: "",
      type: "Language",
      highlight: true,
      logo_url: "/skills/selected-skills/javascript.svg",
    },
    {
      name: "Git",
      level: "",
      type: "Version Control",
      highlight: true,
      logo_url: "/skills/selected-skills/git.svg",
    },
    {
      name: "MySQL",
      level: "",
      type: "Database",
      highlight: true,
      logo_url: "/skills/selected-skills/mysql.svg",
    },
    {
      name: "Node",
      level: "",
      type: "JavaScript Runtime",
      highlight: false,
      logo_url: "/skills/node.svg",
    },
    {
      name: "Npm",
      level: "",
      type: "Package manager",
      highlight: false,
      logo_url: "/skills/npm.svg",
    },
    {
      name: "Prettier",
      level: "",
      type: "Code Formatter",
      highlight: false,
      logo_url: "/skills/prettier.svg",
    },
    {
      name: "Vite",
      level: "",
      type: "Build Tool",
      highlight: false,
      logo_url: "/skills/vite.svg",
    },
    {
      name: "Analytics",
      level: "",
      type: "Data Analysis",
      highlight: false,
      logo_url: "/skills/analytics.svg",
    },
    {
      name: "AWS",
      level: "",
      type: "Cloud",
      highlight: false,
      logo_url: "/skills/aws.svg",
    },
    {
      name: "Axios",
      level: "",
      type: "HTTP Client",
      highlight: false,
      logo_url: "/skills/axios.svg",
    },
    {
      name: "Bootstrap",
      level: "",
      type: "CSS",
      highlight: false,
      logo_url: "/skills/bootstrap.svg",
    },
    {
      name: "Curl",
      level: "",
      type: "Command Line Tool",
      highlight: false,
      logo_url: "/skills/curl.svg",
    },
    {
      name: "Go",
      level: "",
      type: "Language",
      highlight: false,
      logo_url: "/skills/go.svg",
    },
    {
      name: "HTML 5",
      level: "",
      type: "Markup",
      highlight: false,
      logo_url: "/skills/html5.svg",
    },
    {
      name: "Nest JS",
      level: "",
      type: "Framework",
      highlight: false,
      logo_url: "/skills/nestjs.svg",
    },
    {
      name: "Pnpm",
      level: "",
      type: "Package manager",
      highlight: false,
      logo_url: "/skills/pnpm.svg",
    },
    {
      name: "SQL",
      level: "",
      type: "Query",
      highlight: false,
      logo_url: "/skills/sql.svg",
    },
    {
      name: "Yarn",
      level: "",
      type: "Package manager",
      highlight: false,
      logo_url: "/skills/yarn.svg",
    },
    {
      name: "Ubuntu",
      level: "",
      type: "OS",
      highlight: false,
      logo_url: "/skills/ubuntu.svg",
    },
];